### ISSUE TITLE
uniapp编译后的支付宝、抖音小程序不触发组件中的onCreatedXXX钩子

### ISSUE THREAD

**Issue by milo-wjh** [1977474741/spa-custom-hooks#17]
uniapp编译后的支付宝、抖音小程序不触发组件中的onCreatedXXX钩子

**Comment by 1977474741** [comment]
最新版本修复了这个问题https://github.com/1977474741/spa-custom-hooks/commit/a4c1d79d0231c3840e27e0228fdb4cb6ed6e02ff
