### ISSUE TITLE
 uni-app开发的H5  直接通过访问路径进入页面时钩子拿不到options的参数

### ISSUE THREAD

**Issue by COLAXB** [1977474741/spa-custom-hooks#24]
![image](https://user-images.githubusercontent.com/108392933/176380898-c0e164f9-1346-4906-a784-bd3b09381d43.png)
通过nav跳转的方式都能拿到options的参数
![image](https://user-images.githubusercontent.com/108392933/176381339-4da53257-c4ef-486e-928e-ca069e27ee1d.png)

**Comment by milo-wjh** [comment]
遇到了一样的问题，
![`MK@DJ0U({~BV4 Z8)L`T 9](https://user-images.githubusercontent.com/20457324/199205940-a0240c3b-af4f-4499-a0b8-2f0aa2f06e87.png)
![%DZ06X2YX`721K132POT2H0](https://user-images.githubusercontent.com/20457324/199205958-f3b7a692-eaa0-4319-81c7-e1fdbd97664a.png)
发现钩子早于onLoad触发就有options，晚于onLoad的就没有

**Comment by 1977474741** [comment]
> 遇到了一样的问题， ![MK@DJ0U({~BV4 Z8)LT 9](https://user-images.githubusercontent.com/20457324/199205940-a0240c3b-af4f-4499-a0b8-2f0aa2f06e87.png) ![%DZ06X2YX`721K132POT2H0](https://user-images.githubusercontent.com/20457324/199205958-f3b7a692-eaa0-4319-81c7-e1fdbd97664a.png) 发现钩子早于onLoad触发就有options，晚于onLoad的就没有

哪个平台？然后把代码也截个图

**Comment by 1977474741** [comment]
> 遇到了一样的问题， ![MK@DJ0U({~BV4 Z8)LT 9](https://user-images.githubusercontent.com/20457324/199205940-a0240c3b-af4f-4499-a0b8-2f0aa2f06e87.png) ![%DZ06X2YX`721K132POT2H0](https://user-images.githubusercontent.com/20457324/199205958-f3b7a692-eaa0-4319-81c7-e1fdbd97664a.png) 发现钩子早于onLoad触发就有options，晚于onLoad的就没有

h5端原生钩子本身没有onLoad，created里也不会带参数，手动获取参数吧

**Comment by 1977474741** [comment]
> 遇到了一样的问题， ![MK@DJ0U({~BV4 Z8)LT 9](https://user-images.githubusercontent.com/20457324/199205940-a0240c3b-af4f-4499-a0b8-2f0aa2f06e87.png) ![%DZ06X2YX`721K132POT2H0](https://user-images.githubusercontent.com/20457324/199205958-f3b7a692-eaa0-4319-81c7-e1fdbd97664a.png) 发现钩子早于onLoad触发就有options，晚于onLoad的就没有

如果要uniapp全平台的话，看下this，有个当前page参数的对象，uniapp应该做了全平台兼容，无论哪个平台都能拿到

**Comment by 1977474741** [comment]
确实是有这个问题，安装一下最新的包

> 遇到了一样的问题， ![MK@DJ0U({~BV4 Z8)LT 9](https://user-images.githubusercontent.com/20457324/199205940-a0240c3b-af4f-4499-a0b8-2f0aa2f06e87.png) ![%DZ06X2YX`721K132POT2H0](https://user-images.githubusercontent.com/20457324/199205958-f3b7a692-eaa0-4319-81c7-e1fdbd97664a.png) 发现钩子早于onLoad触发就有options，晚于onLoad的就没有
