### ISSUE TITLE
uniapp onCreatedxxx钩子在index.vue页面不触发，编译到微信小程序

### ISSUE THREAD

**Issue by yik7707** [1977474741/spa-custom-hooks#32]
如下代码所示，请问哪里出问题了：
![image](https://github.com/1977474741/spa-custom-hooks/assets/74293458/7e0f7e53-45b6-471d-a0b1-ba2529b9cd4e)
![image](https://github.com/1977474741/spa-custom-hooks/assets/74293458/4f5b0300-a67f-4e86-b696-628506d1c01e)
在App.vue，将本地缓存或请求的数据赋值给userinfo：
![image](https://github.com/1977474741/spa-custom-hooks/assets/74293458/d6c8f99a-940c-4eaf-a96c-3983e2060d48)
index.vue，在首页打印没打印出：
![image](https://github.com/1977474741/spa-custom-hooks/assets/74293458/31150701-d977-446e-9c17-22df4e1eb6ba)
将上面方法写在methods里也一样没打印出
![image](https://github.com/1977474741/spa-custom-hooks/assets/74293458/b11d49e3-cb09-47e6-bc48-9a9cf1b4050c)
最后编译到微信小程序打印没打出来：
![image](https://github.com/1977474741/spa-custom-hooks/assets/74293458/092ab62a-eb8d-47f3-b8c3-710e25c99cad)

**Comment by 1977474741** [comment]
userinfo的i大小写不统一，你看下
