### ISSUE TITLE
项目初次进入无法触发自定义hook

### ISSUE THREAD

**Issue by gkils** [1977474741/spa-custom-hooks#36]
**app.js**

import CustomHook from 'spa-custom-hooks';

let globalData = {
    token: '',
    userInfo: null,
    selectedSchool: null
}

CustomHook.install({
    'Login': {
        name: 'Login',
        watchKey: 'token',
        onUpdate(val) {
            //有token则触发此钩子
            return !!val;
        }
    },
    'User': {
        name: 'User',
        watchKey: 'userInfo.id',
        onUpdate(val) {
            //获取到userinfo里的userId则触发此钩子
            return !!val;
        }
    }
}, globalData || 'globalData')

// 获取用户信息
        let userInfo = wx.getStorageSync('userInfo')
        if (!userInfo) {
            userInfo = await Api.userApi.getUserInfo();
            wx.setStorageSync('userInfo', userInfo)
        }
        this.globalData.userInfo = userInfo
        console.log("app.js获取到用户ID：" + this.globalData.userInfo.id)`

**page.js**

onLoadUser(options) {
        console.log("school页面进入登录回调逻辑")
        this.setData({
            userInfo: app.globalData.userInfo
        })
        console.log(app.globalData.userInfo)
        console.log(this.data.userInfo)
        const location = wechat.getLocation('wgs84')
        const locationParams = {
            longitude: location.longitude || null,
            latitude: location.latitude || null
        }
        this.listSchool(locationParams)
    },
    onLoad() {
        console.log("school页面进入onLoad")
    }

**日志内容**

school页面进入onLoad
dict.js? [sm]:11 1702870222000
dict.js? [sm]:13 
app.js? [sm]:97 app.js获取到用户ID：1735194858279395330

**Comment by 1977474741** [comment]
把watchKey改成userInfo，不要监听内部的id，因为你改的是外面userInfo的引用
