### ISSUE TITLE
typescript版本的微信小程序使用

### ISSUE THREAD

**Issue by DingPengfei** [1977474741/spa-custom-hooks#45]
在TS开发的微信小程序中使用改hooks出现了
`Error: module 'spa-custom-hooks.js' is not defined, require args is 'spa-custom-hooks'`
的错误

**Comment by 1977474741** [comment]
怎么引用的？

**Comment by DingPengfei** [comment]
模块引入了，但是好像一直没注册成功。请问有ts注册的demo吗

**Comment by 1977474741** [comment]
ts跟js一样的方式，没注册成功具体是？有报错吗

**Comment by DingPengfei** [comment]
没有报错，但是也没按照预期：等待token获取再调用后续接口

**Comment by DingPengfei** [comment]
`

   let globalData = {
  token: '',
  userInfo: {
    avatarUrl: '',
    nickName: ''
  }
}

  CustomHook.install({
    'Login':{
      name:'Login',
      watchKey: 'token',
      onUpdate(token: string){
        console.log("触发Login勾子")
        //有token则触发此钩子
        return !!token;
      }
    },
   'User':{
      name:'User',
      watchKey: 'userInfo.nickName',
      onUpdate(nickName: string){
        console.log('触发User勾子')
        //获取到userinfo里的nickName则触发此钩子
        return !!nickName;
      }
    }
  }, globalData || 'globalData')

    // 登录
    wx.login({
      success: res => {
        if (res.code) {
        // 发送 res.code 到后台换取 openId, sessionKey, unionId
          let params = {
            code: res.code
          }
          onLogin(params).then(
            (resp: any) => {
              // TODO set token
              if (resp.data && resp.data.data) {
                globalData.userInfo = resp.data.data;
                // set 登录接口的返回结果
                // TODO 存storage 还是 app
                wx.setStorageSync('token', resp.data.data.token)
                if (resp.data.data.nickName === null) {              // Check if login_res resp has nickName
                  // Jump to landing page
                  wx.navigateTo({
                    url: '/pages/landing/landing'
                  })
                }
              }
              console.log("登录成功")
            }
          )
        } else {
          console.log('登录失败！' + res.errMsg)
        }
      },
    })
`

**Comment by 1977474741** [comment]
在页面中怎么用的？看看代码，用的是login还是user，login的话你给token赋值了吗

**Comment by DingPengfei** [comment]
> 在页面中怎么用的？看看代码，用的是login还是user，login的话你给token赋值了吗

成功了，问题是没给global的token赋值，写到storageSync了。

感谢🌹
